name: "Dev Terraform Workflow"


on:
  pull_request:
    branches:
    - main 


  push:
    branches:
    - feature/**
    - main

permissions: 
  id-token: write
  contents: read


env:
  TF_WORKING_DIR: environments/dev

jobs:
  terraform-plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    environment: dev
    
    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_WORKING_DIR: environments/dev
      
    steps:
      - name: Checkout
        uses: actions/checkout@v7.0.1

      - name: Azure Login
        uses: Azure/login@v2.3.1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2.0.3

      - name: Terraform Format Check
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform fmt -check -recursive

      - name: Terraform Init
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform init 

      - name: Terraform Validate
        working-directory: ${{ env.TF_WORKING_DIR }}
        run: terraform validate

      # - name: Terraform Security Scan
      #   uses: aquasecurity/trivy-action@v0.36.0
      #   with:
      #     scan-type: config
      #     scan-ref: .
      #     exit-code: 1
      #     severity: HIGH,CRITICAL

      - name: Terraform Plan
        working-directory: ${{ env.TF_WORKING_DIR }}
        # env:
        #   TF_VAR_sql_admin_password: ${{ secrets.sql_admin_password }}
        run: 
          terraform plan -out=tfplan

      - name: Upload Terraform Plan
        if: github.event_name == 'push' && github.ref == 'refs/heads/main'
        uses: actions/upload-artifact@v7.0.1
        with:
          name: terraform-plan
          path: ${{ env.TF_WORKING_DIR }}/tfplan
          retention-days: 1

  terraform-apply:
    name: Terraform Apply
    needs: 
    - terraform-plan
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    environment: dev

    env:
      ARM_USE_OIDC: true
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      TF_WORKING_DIR: environments/dev
    
    steps:
    - name: Checkout
      uses: actions/checkout@v7.0.1

    - name: Azure Login
      uses: Azure/login@v2.3.1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3

    - name: Terraform Init
      working-directory: ${{ env.TF_WORKING_DIR }}
      run: terraform init

    - name: Download Terraform Plan
      uses: actions/download-artifact@v4.3.0
      with:
        name: terraform-plan
        path: ${{ env.TF_WORKING_DIR }}

    - name: Terraform Apply
      working-directory: ${{ env.TF_WORKING_DIR }}
      # env:
      #   TF_VAR_sql_admin_password: ${{ secrets.sql_admin_password }}
      run: terraform apply --auto-approve tfplan
    
